import type { NextRequest } from "next/server";
import { z } from "zod";
import { requireLinkedDoctor } from "@/lib/auth/guards";
import { parseBody, uuidSchema } from "@/lib/api/validate";
import { ApiError, handleApiError, ok } from "@/lib/api/errors";
import { createReferral, listReferralsForDoctor, type ReferralStatus } from "@/lib/referrals/service";

export const dynamic = "force-dynamic";

const STATUSES: ReferralStatus[] = ["pending", "accepted", "in_progress", "declined", "completed", "revoked", "expired"];

// Only ids and the doctor's own text are accepted: the patient and clinic are
// taken from the consultation server-side, never from the request.
const createSchema = z.object({
  // One random key per intended referral (generated by the client when the
  // doctor confirms the review step); repeats of the request replay it.
  idempotencyKey: uuidSchema,
  appointmentId: uuidSchema,
  referredToDoctorId: uuidSchema,
  reason: z.string().trim().min(3, "Yo‘llanma sababini yozing").max(2000),
  handoffNote: z.string().trim().max(4000).optional(),
  priority: z.enum(["routine", "urgent"]).default("routine"),
  validForDays: z.union([z.literal(30), z.literal(60), z.literal(90), z.literal(180)]).optional(),
});

/**
 * The calling doctor's referrals: ?box=incoming (default) or ?box=outgoing,
 * optionally narrowed to one status (?status=pending for the dashboard).
 */
export async function GET(request: NextRequest) {
  try {
    const doctor = await requireLinkedDoctor();
    const params = request.nextUrl.searchParams;
    const box = params.get("box") === "outgoing" ? "outgoing" : "incoming";
    const status = params.get("status");
    if (status !== null && !STATUSES.includes(status as ReferralStatus)) {
      throw new ApiError(400, "Noto‘g‘ri holat", "validation");
    }
    return ok({ referrals: await listReferralsForDoctor(doctor, box, (status as ReferralStatus | null) ?? undefined) });
  } catch (e) {
    return handleApiError(e);
  }
}

/** Refers the patient of one of the calling doctor's consultations to a colleague. */
export async function POST(request: NextRequest) {
  try {
    const doctor = await requireLinkedDoctor();
    const body = await parseBody(request, createSchema);
    const referral = await createReferral(doctor, body);
    // 201 for the referral this request created, 200 when it repeats one.
    return ok({ referral }, { status: referral.replayed ? 200 : 201 });
  } catch (e) {
    return handleApiError(e);
  }
}
