"use client";
import {useState} from "react";
import {adminApi,formatDateTime} from "@/lib/admin/client";
import {AButton,AError,AInput,ASelect,Card,PageHeader} from "@/components/admin/ui";
type Patient={id:string;full_name:string;patient_number:number;phone:string|null};
type Payment={id:string;amount:number;currency:string;status:string;created_at:string;visits:{queue_number:number;queue_date:string;status:string;services:{name:string};doctors:{name:string}}};
export default function Cashier(){const [q,setQ]=useState("");const [patients,setPatients]=useState<Patient[]>([]);const [selected,setSelected]=useState<Patient|null>(null);const [payments,setPayments]=useState<Payment[]>([]);const [method,setMethod]=useState("cash");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function search(){setBusy(true);setError("");try{setPatients((await adminApi.get<{patients:Patient[]}>(`/api/operations/patients?q=${encodeURIComponent(q)}`)).patients);}catch(e){setError(e instanceof Error?e.message:"Qidirilmadi");}finally{setBusy(false);}}
 async function load(p:Patient){setSelected(null);setError("");try{setPayments((await adminApi.get<{payments:Payment[]}>(`/api/operations/payments?patientId=${p.id}`)).payments);setSelected(p);}catch(e){setError(e instanceof Error?e.message:"Yuklanmadi");}}
 async function settle(p:Payment,status:string){const reason=status==="refunded"?window.prompt("Qaytarish sababi (pul qaytarilganini tasdiqlang)"):undefined;if(status==="refunded"&&!reason)return;if(!window.confirm(`${p.amount.toLocaleString()} ${p.currency} — ${status==="paid"?"pul qabul qilindi":"pul qaytarildi"}?`))return;setBusy(true);try{await adminApi.post("/api/operations/payments",{id:p.id,expectedStatus:p.status,status,...(reason?{reason}:{method})});if(selected)await load(selected);}catch(e){setError(e instanceof Error?e.message:"Saqlanmadi");}finally{setBusy(false);}}
 return <div><PageHeader title="Xizmatlar kassasi" subtitle="Ro‘yxatdan o‘tgan bemorning narxini tekshiring, keyin qabul qilingan pulni qayd eting."/>{error&&<AError message={error}/>}<Card className="mb-4 space-y-3"><label className="block text-sm">Bemor raqami, ism yoki telefon<AInput value={q} onChange={setQ}/></label><AButton loading={busy} disabled={q.trim().length<2&&!/^\d$/.test(q.trim())} onClick={()=>void search()}>Qidirish</AButton>{patients.map(p=><button key={p.id} className="block w-full rounded-lg border border-hairline p-3 text-left" onClick={()=>void load(p)}>{p.full_name} · №{p.patient_number} · {p.phone}</button>)}</Card>{selected&&<><h2 className="my-4 text-lg font-semibold">{selected.full_name} · №{selected.patient_number}</h2><div className="mb-4 max-w-xs"><ASelect value={method} onChange={setMethod} options={[{value:"cash",label:"Naqd pul"},{value:"terminal",label:"Bank terminali (karta)"}]}/></div><div className="space-y-3">{payments.length===0?<Card>Xizmat uchun to‘lov topilmadi.</Card>:payments.map(p=><Card key={p.id} className="space-y-2"><h3 className="font-semibold">{p.visits.services.name} · {p.visits.doctors.name}</h3><p className="text-xs text-ink-muted">Talon {p.visits.queue_number} · {formatDateTime(p.created_at)}</p><p>{p.amount.toLocaleString()} {p.currency} · {p.status==="paid"?"To‘langan":p.status==="refunded"?"Qaytarilgan":p.status==="voided"?"Bekor qilingan hisob":"To‘lov kutilmoqda"}</p>{p.status==="unpaid"&&p.visits.status!=="cancelled"&&<AButton loading={busy} onClick={()=>void settle(p,"paid")}>Pul qabul qilinganini tasdiqlash</AButton>}{p.status==="paid"&&<AButton variant="outline" loading={busy} onClick={()=>void settle(p,"refunded")}>To‘liq qaytarishni qayd etish</AButton>}</Card>)}</div><p className="mt-4 text-xs text-ink-muted">Bu ichki to‘lov qaydi. Fiskal va bank terminali cheklari amaldagi kassa vositalaridan beriladi. Chek nusxasi alohida to‘lov emas.</p></>}</div>;
}
