"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { adminApi, formatDateTime } from "@/lib/admin/client";
import { AButton, AError, AInput, ASelect, Card, PageHeader, LoadingRow } from "@/components/admin/ui";
type Referral={id:string;patient_id:string;status:string;expires_at:string|null;referral_reason:string;clinical_handoff_note:string|null;created_at:string;patient:{full_name:string};referring_doctor:{name:string};referred_to_doctor:{name:string}};
const active=(r:Referral)=>["pending","accepted","in_progress"].includes(r.status)&&!!r.expires_at&&new Date(r.expires_at)>new Date();
export function ReferralList(){const [rows,setRows]=useState<Referral[]|null>(null);const [error,setError]=useState("");useEffect(()=>{adminApi.get<{referrals:Referral[]}>("/api/doctor/referrals").then(d=>setRows(d.referrals)).catch(e=>setError(e.message));},[]);
 return <div><PageHeader title="Yo‘llanmalar" subtitle="Yo‘llanma bemorni kerakli shifokorga yo‘naltiradi. Qabul qilish bosqichi talab qilinmaydi."/>{error&&<AError message={error}/>}<div className="space-y-3">{rows===null?(!error&&<LoadingRow/>):rows.length===0?<Card>Yo‘llanmalar yo‘q. Bemor tarixidan yangi yo‘llanma yarating.</Card>:rows.map(r=><Link className="block" key={r.id} href={`/doctor/referrals/${r.id}`}><Card><p className="font-semibold">{r.patient.full_name}</p><p className="text-sm">{r.referring_doctor.name} → {r.referred_to_doctor.name}</p><p className="text-xs text-ink-muted">{active(r)?"Ochiq":r.status==="completed"?"Yakunlangan":"Yopilgan"} · {formatDateTime(r.created_at)}</p></Card></Link>)}</div></div>;
}
export function NewReferral({patientId}:{patientId?:string}){const [doctors,setDoctors]=useState<{id:string;name:string}[]>([]);const [name,setName]=useState("");const [target,setTarget]=useState("");const [reason,setReason]=useState("");const [notes,setNotes]=useState("");const [key]=useState(()=>crypto.randomUUID());const [busy,setBusy]=useState(false);const [saved,setSaved]=useState<string|null>(null);const [error,setError]=useState("");
 useEffect(()=>{if(!patientId)return;Promise.all([adminApi.get<{doctors:typeof doctors}>("/api/operations/catalog"),adminApi.get<{patient:{full_name:string}}>(`/api/doctor/patients/${patientId}`)]).then(([d,p])=>{setDoctors(d.doctors);setName(p.patient.full_name);}).catch(e=>setError(e.message));},[patientId]);
 async function save(){setBusy(true);try{const d=await adminApi.post<{referral:{id:string}}>("/api/doctor/referrals",{patientId,receivingDoctorId:target,reason,notes,idempotencyKey:key});setSaved(d.referral.id);}catch(e){setError(e instanceof Error?e.message:"Yuborilmadi");}finally{setBusy(false);}}
 return <div><PageHeader title="Bemorni yo‘naltirish" subtitle={name||"Bemor tarixidan shifokorni tanlang"}/>{error&&<AError message={error}/>}<Card className="max-w-2xl space-y-4">{saved?<><p>Yo‘llanma saqlandi. Qabul qiluvchi shifokor umumiy tarixni ochishi mumkin.</p><Link href={`/doctor/referrals/${saved}`}>Yo‘llanmani ochish →</Link></>:!patientId?<Link href="/doctor">Navbatdan bemorni tanlang →</Link>:<fieldset disabled={busy||!name} className="space-y-4"><label className="block text-sm">Qaysi shifokorga<ASelect value={target} onChange={setTarget} options={[{value:"",label:"Shifokorni tanlang"},...doctors.map(d=>({value:d.id,label:d.name}))]}/></label><label className="block text-sm">Yo‘naltirish maqsadi<AInput value={reason} onChange={setReason} maxLength={1000}/></label><label className="block text-sm">Shifokor uchun izoh (ixtiyoriy)<textarea className="mt-1 block min-h-28 w-full rounded-lg border border-hairline p-3" value={notes} onChange={e=>setNotes(e.target.value)} maxLength={10000}/></label><p className="text-xs text-ink-muted">Yo‘llanma 30 kun amal qiladi. U navbat taloni yoki to‘lov tasdig‘i o‘rnini bosmaydi.</p><AButton disabled={!target||!reason.trim()} loading={busy} onClick={()=>void save()}>Yo‘naltirish</AButton></fieldset>}</Card></div>;
}
export function ReferralDetail({id}:{id:string}){const [data,setData]=useState<{referral:Referral;callerRole:string}|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const load=useCallback(async()=>{try{setData(await adminApi.get(`/api/doctor/referrals/${id}`));setError("");}catch(e){setError(e instanceof Error?e.message:"Yuklanmadi");}},[id]);useEffect(()=>{void load();},[load]);async function change(status:string){setBusy(true);try{await adminApi.patch(`/api/doctor/referrals/${id}`,{status});await load();}catch(e){setError(e instanceof Error?e.message:"Saqlanmadi");}finally{setBusy(false);}}
 const r=data?.referral;return <div><PageHeader title="Yo‘llanma" subtitle={r?`${r.referring_doctor.name} → ${r.referred_to_doctor.name}`:undefined}/>{error&&<AError message={error}/>} {!r?(!error&&<LoadingRow/>):<Card className="space-y-4"><h2 className="text-lg font-semibold">{r.patient.full_name}</h2><p className="whitespace-pre-wrap">{r.referral_reason}</p>{r.clinical_handoff_note&&<p className="whitespace-pre-wrap text-sm">{r.clinical_handoff_note}</p>}<p className="text-xs text-ink-muted">{active(r)?`Amal qilish muddati: ${formatDateTime(r.expires_at)}`:"Yo‘llanma yopilgan"}</p>{active(r)&&<div className="flex flex-wrap gap-3"><Link className="rounded-lg border border-hairline px-4 py-2 text-sm" href={`/doctor/patients/${r.patient_id}?referral=${r.id}`}>Tarixni ochish va qayd yozish</Link><AButton loading={busy} onClick={()=>void change("completed")}>Yo‘llanmani yakunlash</AButton>{data?.callerRole==="referring_doctor"&&<AButton variant="outline" loading={busy} onClick={()=>void change("revoked")}>Bekor qilish</AButton>}</div>}</Card>}</div>;
}
