-- Laboratory (Phase 7): sample collection and the lab work queue.
--
-- Three server-only functions move specimens through the existing tables
-- (lab_samples, lab_sample_items, lab_order_items) in one transaction each:
--
--   collect_lab_sample   one tube for one or more items of the same order and
--                        the same sample type. The items must be
--                        ready_for_collection (so a cancelled order, a
--                        cancelled item, or an item still waiting for payment
--                        under the "before collection" policy is refused).
--                        The items are locked first, so of two collectors
--                        racing for the same item exactly one succeeds; the
--                        other is told the item was already collected.
--                        Idempotent on (clinic, collector, creation key): a
--                        repeated submit returns the first sample.
--                        Items → collected. The sample code is generated by
--                        the database (unique in the clinic).
--   receive_lab_sample   the lab accepts the specimen: sample → received,
--                        its collected items → processing.
--   reject_lab_sample    the specimen is unusable: sample → rejected with a
--                        reason, its items return to ready_for_collection
--                        for a new sample. Refused once any item already has
--                        a result.
--
-- Clinic, patient and order come from the order row, never from the caller:
-- a sample can only ever join items of its own order, patient and clinic
-- (also pinned by composite foreign keys and lab_sample_items_validate).
--
-- SECURITY INVOKER: runs as the calling server (service_role) so every table
-- trigger and constraint still applies; signed-in roles cannot call these.

alter table public.lab_samples add column creation_key uuid;

create unique index lab_samples_creation_key_idx
  on public.lab_samples (clinic_id, collected_by, creation_key)
  where creation_key is not null;

-- The creation key is immutable like every other column outside
-- lab_samples_validate's mutable list (lab_assert_only_changed).

-- ---------------------------------------------------------------------------
-- collect_lab_sample
-- ---------------------------------------------------------------------------

create or replace function public.collect_lab_sample(
  p_clinic_id uuid,
  p_order_id uuid,
  p_item_ids uuid[],
  p_collected_by uuid,
  p_notes text default null,
  p_creation_key uuid default null
)
returns table (lab_sample_id uuid, sample_code text, replayed boolean)
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_items uuid[] := coalesce(p_item_ids, '{}');
  v_order public.lab_orders;
  v_existing public.lab_samples;
  v_sample uuid;
  v_code text;
  v_type text;
  v_types integer;
  v_found integer;
  v_tz text;
  v_attempt integer := 0;
  r record;
begin
  if cardinality(v_items) = 0 then
    raise exception 'lab_sample_empty: choose at least one test for the sample';
  end if;
  if cardinality(v_items) > 50 then
    raise exception 'lab_sample_too_large: at most 50 tests per sample';
  end if;
  if (select count(distinct i) from unnest(v_items) i) <> cardinality(v_items) then
    raise exception 'lab_sample_duplicate_item: a test is chosen twice';
  end if;

  -- Lock the items first (in a fixed order, so concurrent collectors cannot
  -- deadlock). Whoever waits here sees the winner's committed sample next.
  perform 1 from public.lab_order_items i
  where i.id = any (v_items) and i.clinic_id = p_clinic_id
  order by i.id
  for update;

  -- Idempotent replay of the same collector's same submit (after the lock,
  -- so a concurrent duplicate submit replays instead of failing).
  if p_creation_key is not null then
    select * into v_existing
    from public.lab_samples s
    where s.clinic_id = p_clinic_id and s.collected_by = p_collected_by and s.creation_key = p_creation_key;
    if found then
      if v_existing.order_id <> p_order_id
         or (select coalesce(array_agg(si.order_item_id order by si.order_item_id), '{}')
             from public.lab_sample_items si where si.sample_id = v_existing.id)
            <> (select array_agg(i order by i) from unnest(v_items) i) then
        raise exception 'lab_sample_key_reused: this request key was already used for a different sample';
      end if;
      return query select v_existing.id, v_existing.sample_code, true;
      return;
    end if;
  end if;

  select * into v_order from public.lab_orders o where o.id = p_order_id and o.clinic_id = p_clinic_id;
  if not found then
    raise exception 'lab_sample_unknown_order: the order is not in this clinic';
  end if;
  if v_order.status <> 'active' then
    raise exception 'lab_sample_order_not_active: the order is %', v_order.status;
  end if;

  -- Re-read the locked items' state.
  v_found := 0;
  for r in
    select i.id, i.status, i.order_id, t.sample_type
    from public.lab_order_items i
    join public.lab_tests t on t.id = i.test_id and t.clinic_id = i.clinic_id
    where i.id = any (v_items) and i.clinic_id = p_clinic_id
    order by i.id
  loop
    v_found := v_found + 1;
    if r.order_id <> p_order_id then
      raise exception 'lab_sample_foreign_item: a test belongs to another order';
    end if;
    if r.status = 'cancelled' then
      raise exception 'lab_sample_item_cancelled: a chosen test was cancelled';
    end if;
    if r.status = 'ordered' then
      raise exception 'lab_sample_item_not_ready: a chosen test is not ready for collection (awaiting payment)';
    end if;
    if r.status <> 'ready_for_collection' then
      raise exception 'lab_sample_item_already_collected: a chosen test already has a sample';
    end if;
  end loop;
  if v_found <> cardinality(v_items) then
    raise exception 'lab_sample_foreign_item: a test is not in this clinic';
  end if;

  select count(distinct lower(btrim(t.sample_type))), min(t.sample_type) into v_types, v_type
  from public.lab_order_items i
  join public.lab_tests t on t.id = i.test_id and t.clinic_id = i.clinic_id
  where i.id = any (v_items);
  if v_types <> 1 then
    raise exception 'lab_sample_mixed_types: tests needing different sample types cannot share one sample';
  end if;

  select c.timezone into v_tz from public.clinics c where c.id = p_clinic_id;

  loop
    v_attempt := v_attempt + 1;
    v_code := to_char(now() at time zone coalesce(v_tz, 'UTC'), 'YYMMDD') || '-'
              || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6));
    begin
      insert into public.lab_samples (clinic_id, patient_id, order_id, sample_code, sample_type, collected_by, notes, creation_key)
      values (p_clinic_id, v_order.patient_id, v_order.id, v_code, v_type, p_collected_by,
              nullif(btrim(coalesce(p_notes, '')), ''), p_creation_key)
      returning id into v_sample;
      exit;
    exception when unique_violation then
      if p_creation_key is not null then
        select * into v_existing
        from public.lab_samples s
        where s.clinic_id = p_clinic_id and s.collected_by = p_collected_by and s.creation_key = p_creation_key;
        if found then
          -- A concurrent request with the same key won the race.
          return query select v_existing.id, v_existing.sample_code, true;
          return;
        end if;
      end if;
      if v_attempt >= 5 then
        raise;
      end if;
    end;
  end loop;

  insert into public.lab_sample_items (sample_id, order_item_id, clinic_id)
  select v_sample, i, p_clinic_id from unnest(v_items) i;

  update public.lab_order_items
  set status = 'collected', status_changed_by = p_collected_by
  where id = any (v_items) and clinic_id = p_clinic_id;

  return query select v_sample, v_code, false;
end;
$$;

-- ---------------------------------------------------------------------------
-- receive_lab_sample / reject_lab_sample
-- ---------------------------------------------------------------------------

create or replace function public.receive_lab_sample(p_clinic_id uuid, p_sample_id uuid, p_received_by uuid)
returns boolean
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_sample public.lab_samples;
begin
  select * into v_sample from public.lab_samples s
  where s.id = p_sample_id and s.clinic_id = p_clinic_id
  for update;
  if not found then
    raise exception 'lab_sample_not_found: the sample is not in this clinic';
  end if;
  if v_sample.status = 'received' then
    return false; -- already received: nothing to do
  end if;
  if v_sample.status <> 'collected' then
    raise exception 'lab_sample_not_collected: the sample is %', v_sample.status;
  end if;

  update public.lab_samples set status = 'received', received_by = p_received_by
  where id = v_sample.id;

  update public.lab_order_items i
  set status = 'processing', status_changed_by = p_received_by
  from public.lab_sample_items si
  where si.sample_id = v_sample.id and si.order_item_id = i.id and i.clinic_id = p_clinic_id
    and i.status = 'collected';
  return true;
end;
$$;

create or replace function public.reject_lab_sample(p_clinic_id uuid, p_sample_id uuid, p_rejected_by uuid, p_reason text)
returns boolean
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_sample public.lab_samples;
begin
  if p_reason is null or btrim(p_reason) = '' then
    raise exception 'lab_sample_reason_required: a rejection needs a reason';
  end if;

  select * into v_sample from public.lab_samples s
  where s.id = p_sample_id and s.clinic_id = p_clinic_id
  for update;
  if not found then
    raise exception 'lab_sample_not_found: the sample is not in this clinic';
  end if;
  if v_sample.status = 'rejected' then
    return false;
  end if;

  -- Lock the sample's items; refuse once any has a result.
  perform 1 from public.lab_order_items i
  join public.lab_sample_items si on si.order_item_id = i.id
  where si.sample_id = v_sample.id
  order by i.id
  for update of i;
  if exists (
    select 1 from public.lab_order_items i
    join public.lab_sample_items si on si.order_item_id = i.id
    where si.sample_id = v_sample.id and i.status not in ('collected', 'processing')
  ) or exists (
    select 1 from public.lab_results r
    join public.lab_sample_items si on si.order_item_id = r.order_item_id
    where si.sample_id = v_sample.id and r.status <> 'superseded'
  ) then
    raise exception 'lab_sample_has_results: a test of this sample already has a result';
  end if;

  update public.lab_samples
  set status = 'rejected', rejected_by = p_rejected_by, reject_reason = btrim(p_reason)
  where id = v_sample.id;

  update public.lab_order_items i
  set status = 'ready_for_collection', status_changed_by = p_rejected_by
  from public.lab_sample_items si
  where si.sample_id = v_sample.id and si.order_item_id = i.id and i.clinic_id = p_clinic_id;
  return true;
end;
$$;

revoke all on function public.collect_lab_sample(uuid, uuid, uuid[], uuid, text, uuid) from public, anon, authenticated;
revoke all on function public.receive_lab_sample(uuid, uuid, uuid) from public, anon, authenticated;
revoke all on function public.reject_lab_sample(uuid, uuid, uuid, text) from public, anon, authenticated;
grant execute on function public.collect_lab_sample(uuid, uuid, uuid[], uuid, text, uuid) to service_role;
grant execute on function public.receive_lab_sample(uuid, uuid, uuid) to service_role;
grant execute on function public.reject_lab_sample(uuid, uuid, uuid, text) to service_role;
